name: uses example
on:
  workflow_dispatch:

jobs:
  uses-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: run python script
        run: python my_script.py
